---
title: "Progress Report"
author: "Alexa Elliott"
date: "2022-04-17"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

View(backin)

```{r}
library(Lahman)
head(HallOfFame, 3)
head(HallOfFame)
View(HallOfFame)
View(People)
View(backin)

```

```{r}
hof <- Lahman::HallOfFame
hof %>% 
  ggplot(aes(x = yearID, y = votes/needed*100, group=playerID)) +
  geom_hline(yintercept = 100, colour="grey70") + 
  geom_line() +
  geom_point(aes(colour = "inducted"), 
    data = hof %>% filter(inducted=="Y")) +
  xlim(c(2000, 2022)) +
  ylab("Percent of votes")
```

```{r}
#view the rows of original table
head(hof, 3)

hof <- select(hof, playerID,  votes, yearID)
head(hof, 3)
```


```{r}
library(rvest)
url <- "https://www.baseball-reference.com/awards/hof_2023.shtml"
html <- read_html(url)
tables <- html_table(html)
View(backin)
```

```{r}
#Removing the X- in front of the names that have it
backin$Name[18:28] <- lapply(backin$Name[18:28], function(x) gsub("X-", "", x))
View(backin)
```

```{r}
library(dplyr)
backin <- backin %>% 
  rename(Name = playerID)

head(backin, 3)
```

```{r}
# Merge backin with People dataset based on the player's name
merged_data <- merge(backin, People, by.x = "Name", by.y = "nameGiven", all.x = TRUE)

head(merged_data)
```

```{r}
matched_row <- People %>% 
  filter(nameGiven == "Scott Rolen")

playerID <- matched_row$playerID

print(playerID)
```



```{r}
#cleaning the scraped data
backin <- select(backin, Name, Votes)
backin$yearID <- 2023

#change names and order to match
backin <- backin %>%
  rename(playerID = Name, votes = Votes)

head(backin, 3)
```



```{r}
#combine using rbind
updated_hof <- rbind(hof, backin)

write.csv(updated_hof, file="hof2023", row.names = FALSE)
```

```{r}
# Merge the datasets on playerID
#merged_data <- merge(hof, backin, by = "playerID", all.x = TRUE)

# View the merged dataset
#View(merged_data)
```




